config/routes.rb
HelpCenter::Application.routes.draw do
  root to: "topics#index"
  match "index" => "topics#index"

  match "search" => "topics#search"
  match "admin/" => "topics#edit_all"

  get "/:id" => "topics#show", as: :show_root_topic

  scope "/admin" do
    resources :topics, except: [:index, :show]
    resources :basic_guides, only: [:new, :create, :update]
    resources :faqs, only: [:new, :create, :update]
    resources :guides, only: [:new, :create, :update]
  end

  resources :topics, only: [:index]
  get "/:root_id/:id" => "topics#show", as: :show_topic

  ActionDispatch::Routing::Translator.translate_from_file('lang/i18n-routes.yml', { :no_prefixes => true })
end

app/models/basic_guide.rb
class BasicGuide < Topic
end

app/models/faq.rb
class Faq < Topic
end

app/models/guide.rb
class Guide < Topic

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :view_count, :title, :body, :icon_name
  is_sluggable :title

  acts_as_nested_set

  validates :title, presence: true
  after_save :reindex_topics

  searchable do
    text :title, boost: 3.0
    text :body
    integer :view_count

    boolean :leaf do
      leaf?
    end

    boolean :parent_faq do
      root.faq?
    end
  end

  def faq?
    self.type == "Faq"
  end

  def guide?
    self.type == "Guide"
  end

  def basic?
    self.type == "BasicGuide"
  end

  def read_more
    leaves = self.root.leaves
    index = leaves.find_index(self)

    if leaves.length == 1 || index.nil?
      return []
    end

    # If there is only one more leaf retrieve only one result
    length = leaves.length == 2 ? 1 : 2

    # If leaf is the last one
    if leaves[index + 1].nil?
      leaves[index - length, length]

    # If leaf is the penultimate one
    elsif leaves[index + 2].nil? && length > 1
      # One before and one after
      [leaves[index - 1], leaves[index + 1]]

    else
      leaves[index + 1, length]
    end
  end

  private

  def reindex_topics
    self.index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      config = HelpCenter::Application.config.user
      username == config[:user_id] && password == config[:user_password]
    end
  end

  private

  def searching
    @search = Topic.search do
      fulltext params[:t]
      with(:leaf, true)
    end
  end

  def top_questions
    @top_questions = Topic.search do
      with(:leaf, true)
      with(:parent_faq, true)
      order_by(:view_count, :desc)
      paginate page: 1, per_page: 5
    end
  end
end

app/controllers/basic_guides_controller.rb
class BasicGuidesController < ApplicationController
  respond_to :html

  before_filter :authenticate

  def new
    @basic_new = BasicGuide.new
  end

  def create
    @basic = BasicGuide.new(params[:basic_guide])
    @basic.save

    redirect_to edit_topic_path(@basic)
  end

  def update
    @basic = BasicGuide.find_using_slug(params[:id])
    @basic.update_attributes(params[:basic_guide])

    redirect_to edit_topic_path(@basic)
  end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  respond_to :html

  before_filter :authenticate

  def new
    @faq_new = Faq.new
  end

  def create
    @faq = Faq.new(params[:faq])
    @faq.save

    redirect_to edit_topic_path(@faq)
  end

  def update
    @faq = Faq.find_using_slug(params[:id])
    @faq.update_attributes(params[:faq])

    redirect_to edit_topic_path(@faq)
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  respond_to :html

  before_filter :authenticate

  def new
    @guide_new = Guide.new
  end

  def create
    @guide = Guide.new(params[:guide])
    @guide.save

    redirect_to edit_topic_path(@guide)
  end

  def update
    @guide = Guide.find_using_slug(params[:id])
    @guide.update_attributes(params[:guide])

    redirect_to edit_topic_path(@guide)
  end
end

app/controllers/topics_controller.rb
# encoding: utf-8
class TopicsController < ApplicationController
  require 'viewable'
  respond_to :html

  before_filter :authenticate, except: [:index, :show, :search]

  include Viewable

  def index
    @guides = Guide.roots
    @basic_guide = BasicGuide.root

    top_questions
  end

  def show
    @topic = Topic.find_using_slug(params[:id])

    if @topic.faq?
      @faq = @topic
      top_questions
      @categories = @faq.children

      render 'faqs/show'
    elsif @topic.guide?
      @guide = @topic
      @children = @guide.children

      render 'guides/show'
    elsif @topic.basic?
      @basic = @topic
      @children = @basic.children

      render 'basic_guides/show'
    elsif @topic.leaf?
      update_view_count(@topic)

      @topic.reload
      @ancestors = @topic.ancestors
      @read_more = @topic.read_more
    else
      @ancestors = @topic.ancestors
      @children = @topic.children

      render 'faqs/category'
    end
  end

  def new
    @topic_new = Topic.new
  end

  def create
    @topic = Topic.create(params[:topic])
    @topic.save

    parent = Topic.find_using_slug(params[:parent_id])
    @topic.move_to_child_of(parent)

    redirect_to edit_topic_path(@topic)
  end

  def edit
    @topic = Topic.find_using_slug(params[:id])
    @topics_and_categories = @topic.descendants
  end

  def update
    @topic = Topic.find_using_slug(params[:id])
    @topic.update_attributes(params[:topic])

    redirect_to edit_topic_path(@topic)
  end

  def destroy
    @topic = Topic.find_using_slug(params[:id])
    @topic.destroy

    redirect_to :root
  end

  def search
    searching

    @results = @search.results
    @results = Kaminari.paginate_array(@results).page(params[:page])
  end

  def edit_all
    @categories = []
    @categories << Faq.roots
    @categories << BasicGuide.roots
    @categories << Guide.roots
    @categories.flatten!

    render 'topics/edit_all'
  end
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  def topic_path_html(topic, without_root = false)
    html = ""
    ancestors = topic.ancestors

    ancestors.shift if without_root

    ancestors.each do |parent|
      html << parent.title
      html << (parent == ancestors.last ? "" : " > ")
    end

    html
  end
end

app/helpers/text_helper.rb
module TextHelper
  def markparser
    parser = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                        :autolink => true,
                                        :space_after_headers => false)

    parser
  end

  def truncate_html(html)
    parsed = Nokogiri::HTML(html)
    count = 0
    parsed.xpath("//body").children.each do |child|
      child.remove if count > 2
      count = count + 1
    end

    parsed.to_html
  end

  def truncate_html_tag(html_text, tag)
    parsed = Nokogiri::HTML(html_text)
    parsed.xpath("//"+tag).each do |img|
      img.remove
      img.text.gsub(/\s+/, " ").strip
    end

    parsed.to_html
  end
end

app/helpers/wymeditor_helper.rb
module WymeditorHelper
  def wymeditor_initialize(*dom_ids)
    output = []
    unless(Rails.env =~ /(production)|(test)/)
      output << javascript_include_tag('wymeditor/wymeditor/jquery.wymeditor.js')
    else
      output << javascript_include_tag('wymeditor/wymeditor/jquery.wymeditor.pack.js')
    end
    output << javascript_include_tag('wymrails.js')
    output.join("\n")
  end
end

app/views/basic_guides/_category_column.html.erb
<div class="basic-guide-column">
  <h3><%= categories.first.title %></h3>

  <ul class="questions-list">
    <%= render partial: categories.first.children, locals: { basic_guide: true }%>
  </ul>
</div>

<div class="basic-guide-column right">
  <h3><%= categories.second.title %></h3>

  <ul class="questions-list">
    <%= render partial: categories.second.children, locals: { basic_guide: true } %>
  </ul>
</div>

app/views/basic_guides/_category_section.html.erb
<hr class="list-separator">

<div class="help-central-section">
  <div class="basic-guide-row">

    <h3 class="icon-<%= category.icon_name %>-black_16_18-before"><%= category.title %></h3>

    <div class="basic-guide-section">
      <ul class="questions-list">
        <%= render partial: category.children, locals: { basic_guide: true } %>
      </ul>
    </div>

    <%= render partial: "basic_guides/category_subsection", collection: category.children, as: :subcategory%>
  </div>
</div>

app/views/basic_guides/_category_subsection.html.erb
<% unless subcategory.leaf? %>
  <div class="basic-guide-section right">
    <h6><%= subcategory.title %></h6>

    <ul class="questions-list">
      <%= render partial: subcategory.children, locals: { basic_guide: true } %>
    </ul>
  </div>
<% end %>

app/views/basic_guides/new.html.erb
<div class="content-body">
  <div class="help-central-header">
    <%=raw wymeditor_initialize %>
    <h1> Novo Guia Básico </h1>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <%= render partial: "shared/form", locals: { item: @basic_new } %>
  </div>
</div>

app/views/basic_guides/show.html.erb
<div class="content-body">
  <%= render partial: "guides/header", locals: { guide: @basic } %>

  <hr class="list-separator">

  <div class="help-central-section">
    <%= render partial: "basic_guides/category_column", locals: { categories: @children.shift(2) } %>
  </div>

  <%= render partial: "basic_guides/category_section", collection: @children, as: :category %>
</div>

app/views/faqs/_categories.html.erb
<div class="faq-category">
  <div class="faq-category-title">
    <h6 class="icon-frequent-questions-lightgray_32_34-before"><%= category.title %></h6>
  </div>

  <ul class="list-button">
    <%= render partial: "faqs/item_categories",
      collection: category.children, as: :category_item%>
  </ul>
</div>

app/views/faqs/_item_categories.html.erb
<li class="list-button-item link-container">
  <%= link_to show_topic_path(category_item.root, category_item), title: category_item.title, class: "list-button-link link-target icon-frequent-questions-lightblue_16_18-before" do %>
    <h6><%= category_item.title %></h6>
  <% end %>
  <div class="list-lecture-info">
    <span class="wall-stats icon-doubt-topic-gray_16_18-before legend"><%= t(:questions, count: category_item.children.count) %></span>
  </div>
</li>

app/views/faqs/category.html.erb
<div class="content-body">
  <div class="help-central-header">

    <a href="#" class="title icon-frequent-questions-lightblue_32_34-before">
      <h2 class="hide-title">
        <%= @topic.root.title %>
      </h2>
    </a>

    <%= render partial: "shared/small_search_form" %>

    <span class="subtitle hide-title legend"><%= topic_path_html(@children.first, true) %></span>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <h3><%= @topic.title %></h3>

    <span class="questions legend"><%= t(:questions, count: @children.count) %></span>

    <ul class="questions-list">
      <%= render partial: @children, locals: { with_path: true } %>
    </ul>
  </div>

  <hr class="list-separator">

  <%= render :partial => "shared/feel_supported", :locals => { :index => false } %>
</div>

app/views/faqs/new.html.erb
<div class="content-body">
  <div class="help-central-header">
    <%=raw wymeditor_initialize %>
    <h1> Nova Faq </h1>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <%= render partial: "shared/form", locals: { item: @faq_new } %>
  </div>
</div>

app/views/faqs/show.html.erb
<div class="content-body">
  <div class="help-central-header">
    <%= link_to "#", class: "title icon-#{ @faq.icon_name }-lightblue_32_34-before" do %>
      <h2 class="hide-title"><%= @faq.title %></h2>
    <% end %>

    <%= render partial: "shared/small_search_form" %>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <h3><%= t(:frequently_questions) %></h3>

    <ul class="questions-list">
      <%= render partial: @top_questions.results, locals: { with_path: true }  %>
    </ul>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <h3><%= t(:doubts_by_category) %></h3>

    <%= render partial: "faqs/categories", collection: @categories, as: :category %>
  </div>
</div>

app/views/guides/_categories.html.erb
<hr class="list-separator">

<div class="help-central-section">
  <h3 class="icon-<%= category.icon_name %>-black_16_18-before"><%= category.title %></h3>

  <ul class="questions-list">
    <%= render partial: category.children %>
  </ul>
</div>

app/views/guides/_guide.html.erb
<li class="guides-list-item link-container">
  <div class="guides-list-item-header">
    <span class="guides-list-item-icon icon-<%= guide.icon_name %>-lightblue_32_34-before text-replacement"><%= guide.title %></span>
  </div>
  <div class="guides-list-item-body">
    <h4>
      <%= link_to guide.title, show_root_topic_path(guide), class: "guides-list-item-title link-target" %>
    </h4>
  </div>
  <div class="guides-list-item-footer">
    <p class="legend"><%= guide.body %></p>
  </div>
</li>

app/views/guides/_header.html.erb
<div class="help-central-header">
  <%= link_to "#", class: "title icon-#{ guide.icon_name }-lightblue_32_34-before" do %>
    <h2 class="hide-title"><%= guide.title %></h2>
  <% end %>

  <%= render partial: "shared/small_search_form" %>
</div>

app/views/guides/new.html.erb
<div class="content-body">
  <div class="help-central-header">
    <%=raw wymeditor_initialize %>
    <h1> Nova Guia </h1>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <%= render partial: "shared/form", locals: { item: @guide_new } %>
  </div>
</div>

app/views/guides/show.html.erb
<div class="content-body">
  <%= render partial: "guides/header", locals: { guide: @guide } %>

  <%= render partial: "guides/categories", collection: @children, as: :category %>

  <hr class="list-separator">

  <%= render :partial => "shared/feel_supported", :locals => { :index => false } %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if gt IE 8]><html class="gt-ie8" lang="pt-br"><![endif]-->
<!--[if gt IE 8]><!--><html lang="pt-br"><!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <title><%= t(:help_center) %> — Redu</title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags  %>
  </head>
  <body>
    <%= render partial: "shared/navigation_global" %>
    <div class="main-wrapper">
      <div class="container">
        <div class="row">
          <div class="span3">
            <div class="help-central-sidebar white-area">
              <h2 class="help-central-title">
                <%= link_to t(:help_center), root_path,
                  class: "help-central-link icon-help-central-gray_66-before",
                  title: t(:help_center) %>
              </h2>
              <%= render_navigation(context: :help_central_nav_local, renderer: NavLocal) %>
            </div>
          </div>
          <div class="span13">
            <div class="help-central-content">
              <%= render_navigation(context: :breadcrumbs, renderer: CustomBreadcrumbs) %>
              <%= yield %>
              <%= render_navigation(context: :breadcrumbs, white: true, renderer: CustomBreadcrumbs)%>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-pusher"></div>
    </div>
    <%= render partial: "shared/footer" %>
    <%= render partial: "shared/olark" %>
    <%= render partial: "shared/analytics" %>
  </body>
</html>

app/views/shared/_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-13202852-1']);
  _gaq.push(['_setDomainName', 'redu.com.br']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/shared/_big_search_form.html.erb
<div class="section-question">
  <h3 class="help-central-title-question"><%= question %></h3>
</div>

<hr class="list-separator">

<div class="section-form">
  <div class="row">
    <div class="span11 offset1">
      <%= form_tag search_path, method: :get, class: "form-search control-big" do %>
        <%= text_field_tag :t, params[:t], class: "control-area",
          placeholder: t(:placehold_big_form) %>
        <button class="control-append-area button-default button-big" type="submit">
          <span class="control-search-icon icon-magnifier-gray_16_18 text-replacement"><%= t(:search) %></span>
        </button>
      <% end %>
    </div>
  </div>
</div>

<hr class="list-separator">

app/views/shared/_feel_supported.html.erb
<div class="section">
  <h3 class="icon-feel-supported-gray_32_34-before feel-supported-title<%= ' feel-supported-title-index' if index %>"><%= t(:feel_supported) %></h3>
  <div class="feel-supported-areas">
    <div class="feel-supported-area icon-talk-to-us-green_48_50-before">
      <h4 class="feel-supported-sub-title"><%= t(:help_us) %></h4>
      <p><%= t(:help_us_explanation) %>, <%= link_to t(:talk_with_us), "http://www.redu.com.br/contato", title: t(:talk_with_us) %>.</p>
    </div>
    <div class="feel-supported-area icon-say-hi-green_48_50-before">
      <h4 class="feel-supported-sub-title"><%= t(:talk_online) %></h4>
      <p><%= t(:talk_online_explanation) %> <%= link_to t(:say_hello), "javascript:void(0);", onclick: "olark('api.box.expand')", title: t(:oracle) %>.</p>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="span4">
        <div class="footer-logo-wrapper">
          <%= link_to "http://tech.redu.com.br/",
              :class => "footer-logo-link" do %>
              <h1 class="footer-logo-img sprite-logo-redu-tech-footer text-replacement">Redu Educational Technologies</h1>
          <% end %>
          <span class="footer-cnpj">CNPJ: 12.359.885 / 0001-07</span>
        </div>
      </div>
      <div class="span3">
        <ul class="footer-navigation">
          <li>
            <%= link_to "Sobre o Redu",
                "http://www.redu.com.br/",
                :title => "Sobre o Redu"
            %>
          </li>
          <li>
            <%= link_to "Segmentos",
                "http://www.redu.com.br/#segmentos",
                :title => "Segmentos",
                :class => "landing-scroll"
            %>
          </li>
          <li>
            <%= link_to "Vantagens",
                "http://www.redu.com.br/#vantagens",
                :title => "Vantagens",
                :class => "landing-scroll"
            %>
          </li>
          <li>
            <%= link_to "Funcionalidades",
                "http://www.redu.com.br/#funcionalidades",
                :title => "Funcionalidades",
                :class => "landing-scroll"
            %>
          </li>
          <li>
            <%= link_to "Planos",
                "http://www.redu.com.br/#planos",
                :title => "Planos",
                :class => "landing-scroll"
            %>
          </li>
        </ul>
      </div>
      <div class="span3">
        <ul class="footer-navigation">
          <li>
            <%= link_to "Blog",
                "http://blog.redu.com.br/",
                :title => "Blog"
            %>
          </li>
          <li>
            <%= link_to "Desenvolvedores",
                "http://developers.redu.com.br/",
                :title => "Desenvolvedores"
            %>
          </li>
          <li>
            <%= link_to "Política de Privacidade",
                "#modal-privacy-policy",
                :title => "Política de Privacidade",
                "data-toggle" => "modal"
            %>
          </li>
          <li>
            <%= link_to "Termos de Uso",
                "#modal-tos",
                :title => "Termos de Uso",
                "data-toggle" => "modal"
            %>
          </li>
        </ul>
        <%= render :partial => "shared/modal_tos" %>
        <%= render :partial => "shared/modal_privacy_policy" %>
      </div>
      <div class="span3">
        <div class="footer-social-networks-legend">
          <span class="legend">Siga-nos na web</span>
        </div>
        <div class="footer-social-networks">
          <%= link_to "Facebook", "https://www.facebook.com/redesocialeducacional", :class => "footer-social-network sprite-social-facebook text-replacement", :title => "Facebook" %>
          <%= link_to "Twitter", "http://twitter.com/redu_ead", :class => "footer-social-network sprite-social-twitter text-replacement", :title => "Twitter" %>
        </div>
      </div>
      <div class="span3">
        <div class="footer-contact link-container">
          <div class="row">
            <div class="span2">
              <h3>
                <%= link_to "Fale Conosco",
                      "http://www.redu.com.br/contato",
                      :title => "Fale Conosco",
                      :class => "link-target"
                %>
              </h3>
              <p class="legend">Dúvidas? Nosso suporte online pode lhe ajudar</p>
            </div>
            <div class="span1 alpha-half">
              <span class="footer-talk-to-us-balloons sprite-talk-to-us text-replacement" title="Fale Conosco">Fale conosco</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<%= form_for item do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :icon_name %>
  <%= f.text_field :icon_name %>

  <%= f.label :body %>
  <%= f.text_area :body, class: 'wymeditor' %>

  <%= hidden_field_tag :parent_id, params[:parent_id] %>

  <input class="button-default"<%= f.submit %></input>
<% end %>

app/views/shared/_olark.html.erb
<noscript><a href="https://www.olark.com/site/4636-482-10-5595/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>

app/views/shared/_small_search_form.html.erb
<%= form_tag search_path, method: :get, class: "form-search" do %>
  <%= text_field_tag :t, params[:t], class: "control-area",
    placeholder: t(:placehold_small_form), "data-toggle" => ".hide-title"%>
  <button class="control-append-area button-default" type="submit">
    <span class="control-search-icon icon-magnifier-gray_16_18 text-replacement"><%= t(:search) %></span>
  </button>
<% end %>

app/views/topics/_basic_guide.html.erb
<li class="guides-list-item guides-list-item-basic link-container">
  <div class="guides-list-item-header">
    <span class="guides-list-item-icon icon-<%= @basic_guide.icon_name %>-green_32_34-before text-replacement"><%= @basic_guide.title %></span>
  </div>
  <div class="guides-list-item-body">
    <h4>
      <%= link_to @basic_guide.title, show_root_topic_path(@basic_guide), class: "guides-list-item-title link-target" %>
    </h4>
    <em class="legend"><%= t(:start_here) %></em>
  </div>
  <div class="guides-list-item-footer">
    <p class="legend"><%= @basic_guide.body %></p>
  </div>
</li>

app/views/topics/_topic.html.erb
<% # If the topic isn't leaf and belongs to a basic guide nothing happens %>

<% basic_guide ||= false %>
<% read_more ||= false %>
<% with_path ||= false %>
<% search ||= false %>

<% unless !topic.leaf? && basic_guide %>

  <% if topic.leaf? %>
    <li class="question-list-item <% if read_more %> item-gray <% end %>">
      <span class="icon-<%= search ? 'doubt-topic' : topic.icon_name %>-gray_16_18 text-replacement question-list-icon">Ícone</span>
      <div class="question-list-content">
        <%= link_to topic.title, show_topic_path(topic.root, topic), class: "question-list-link" %>

        <% if search %>
          <span class="question-list-description legend">
            <% text = markparser.render(topic.body) %>
            <%= raw strip_tags(truncate_html(truncate_html_tag(text, "img"))) %>
          </span>
        <% end %>

        <% if read_more %>
          <span class="legend"><%= topic_path_html(topic) %></span>
        <% elsif with_path %>
          <span class="legend"><%= t(:visualizations, count: topic.view_count) %> — <%= topic_path_html(topic) %></span>
        <% else %>
          <span class="legend"><%= t(:visualizations, count: topic.view_count) %></span>
        <% end %>

      </div>
    </li>

  <% else %>
    <h6 class="guide-subtopic"><%= topic.title %></h6>
    <ul class="questions-list">
      <%= render partial: topic.children %>
    </ul>
  <% end %>

<% end %>

app/views/topics/edit.html.erb
<div class="content-body">
  <div class="help-central-header">
    <%=raw wymeditor_initialize %>
    <h2> Editar <%= @topic.title %> </h2>
    <%= link_to "Adicionar topico", new_topic_path(parent_id: @topic) %>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <%= render partial: "shared/form", locals: { item: @topic } %>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <ul class="list-button">
      <% @topics_and_categories.each do |item| %>
        <li class="list-button-item">
          <h6><a><%= item.title %></a></h6>
          <div class="list-lecture-info">
            <%= link_to "Editar", edit_topic_path(item) %>
            <%= link_to "Adicionar topico", new_topic_path(parent_id: item) %>
            <%= link_to "Remover topico", topic_path(item),
              confirm: "Tem certeza que deseja remover?", method: :delete %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/topics/edit_all.html.erb
<div class="content-body">
  <div class="help-central-header">
    <%=raw wymeditor_initialize %>
    <h2> Editar Central de Ajuda </h2>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <%= link_to "Adicionar Faq", new_faq_path %>
    <%= link_to "Adicionar Guia Basico", new_basic_guide_path %>
    <%= link_to "Adicionar Guia", new_guide_path %>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <ul class="list-button">
      <% @categories.each do |item| %>
        <li class="list-button-item">
          <h6><a><%= item.title %></a></h6>
          <div class="list-lecture-info">
            <%= link_to "Editar", edit_topic_path(item) %>
            <%= link_to "Adicionar topico", new_topic_path(parent_id: item) %>
            <%= link_to "Remover topico", topic_path(item), confirm: "Tem certeza que deseja remover?", method: :delete %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/topics/show.html.erb
<div class="content-body">

  <div class="help-central-header">

    <a href="<%= show_root_topic_path(@ancestors.first) %>" class="article title icon-<%= @ancestors.first.icon_name %>-gray_32_34-before">
      <h2 class="hide-title">
        <%= @ancestors.first.title %>
      </h2>
    </a>

    <%= render partial: "shared/small_search_form" %>

    <span class="subtitle hide-title legend"><%= topic_path_html(@topic, true) %></subtitle>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <div class="article">
      <h3><%= @topic.title %></h3>
      <%= raw markparser.render(@topic.body) %>
    </div>
  </div>

  <hr class="list-separator">

  <div class="help-central-section">
    <h3 class="title-gray"><%= t(:read_more) %></h3>

    <%= render partial: "topics/read_more", locals: { more: @read_more }%>
  </div>

  <hr class="list-separator">

  <div class="help-central-footer">
    <p class="article"><%= t(:article_from) %> <%= link_to @ancestors.first.title, show_root_topic_path(@ancestors.first) %>, <%= t(:chapter) %> “<%= topic_path_html(@topic, true) %>”.</p>
  </div>
</div>